// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN5kHwQmH1yUvmB8_R_zJk_rkSER9GFeM',
    appId: '1:167366749510:web:180c6330d3a06dc2a40947',
    messagingSenderId: '167366749510',
    projectId: 'crud-from-zero-f79e1',
    authDomain: 'crud-from-zero-f79e1.firebaseapp.com',
    storageBucket: 'crud-from-zero-f79e1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC4BkiNzR9lIxYbVLn27gJyxXWkYXP_wc',
    appId: '1:167366749510:android:fe2608a22df6ce14a40947',
    messagingSenderId: '167366749510',
    projectId: 'crud-from-zero-f79e1',
    storageBucket: 'crud-from-zero-f79e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMJ4T69OpWqkjqXx3W6itOrXqMgaUKQpI',
    appId: '1:167366749510:ios:5b37f4dea1331f15a40947',
    messagingSenderId: '167366749510',
    projectId: 'crud-from-zero-f79e1',
    storageBucket: 'crud-from-zero-f79e1.appspot.com',
    iosClientId: '167366749510-a9evnrqf5hauj2vl0idq68lqfmrf3hln.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudfromzero',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMJ4T69OpWqkjqXx3W6itOrXqMgaUKQpI',
    appId: '1:167366749510:ios:5b37f4dea1331f15a40947',
    messagingSenderId: '167366749510',
    projectId: 'crud-from-zero-f79e1',
    storageBucket: 'crud-from-zero-f79e1.appspot.com',
    iosClientId: '167366749510-a9evnrqf5hauj2vl0idq68lqfmrf3hln.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudfromzero',
  );
}
